=== timaschew/omt/OMT-engine/schema/Leadsheets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://freebits.de/OMT-engine/schemas/Leadsheets" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:mdb="http://freebits.de/OMT-engine/schemas/Leadsheets">


    <element name="leadsheets" type="mdb:leadsheetsNodeType">
    	<annotation>
    		<documentation>Wurzelknoten des Leadsheet-Modells</documentation>
    	</annotation></element>
    
    <complexType name="leadsheetsNodeType">
    	<annotation>
    		<documentation>Liste aller Leadsheets
    		</documentation>
    	</annotation>
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="leadsheet" type="mdb:leadsheetNodeType"></element>
    	</sequence>
    	<attribute name="num" type="nonNegativeInteger"></attribute>
    </complexType>

    <complexType name="voiceNodeType">
        <annotation>
        	<documentation>Stimme innerhalb eines Musikstücks</documentation></annotation>
        <attribute name="reference-id" type="int" use="required">
    		<annotation>
    			<documentation>Referenz-ID zur Stimme</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="meaning" type="mdb:meaningAttributeType"
    		use="required">
    		<annotation>
    			<documentation>Stimmenkontext</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="deltatime" type="mdb:deltaTimeAttributeType"
    		use="required">
    		<annotation>
    			<documentation>
    				Relative Zeitangabe für den Einsatzzeitpunkt.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="deltatone" type="mdb:deltatoneAttributeType"
    		use="optional">
    		<annotation>
    			<documentation>TODO: Relativer Versatz zum Grundton der Harmonie?
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="basicnote" type="mdb:basicnodeAttributeType">
    		<annotation>
    			<documentation>TODO: Grundton?</documentation>
    		</annotation></attribute>
    </complexType>

    <simpleType name="meaningAttributeType">
    	<restriction base="string">
    		<enumeration value="chord"></enumeration>
    		<enumeration value="melody"></enumeration>
    		<enumeration value="accompaniment"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="deltaTimeAttributeType">
    	<restriction base="float"></restriction>
    </simpleType>

    <complexType name="leadsheetNodeType">
        <annotation>
        	<documentation>Repräsentation des Leadsheets eines Musikstückes</documentation>
        </annotation>
        <sequence>
    		<element name="voice" type="mdb:voiceNodeType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="id" type="nonNegativeInteger" use="required">
    		<annotation>
    			<documentation>TODO: besser als nonNegativeInteger wäre hier ID, aber dies erlaubt keine Zahl zu Beginn</documentation>
    		</annotation></attribute>
    	<attribute name="is-a-id" type="nonNegativeInteger" use="required">
            <annotation>
            	<documentation>TODO: besser als nonNegativeInteger wäre hier IDREF, aber dies erlaubt keine Zahl zu Beginn</documentation>
            </annotation>
    	</attribute>
    	<attribute name="title" type="string" use="required"></attribute>
    </complexType>

    <simpleType name="deltatoneAttributeType">
    	<restriction base="nonNegativeInteger"></restriction>
    </simpleType>

    <simpleType name="basicnodeAttributeType">
    	<restriction base="nonNegativeInteger"></restriction>
    </simpleType>

</schema>

=== timaschew/omt/trunk/OMT-Engine/schema/Leadsheets.xml
<?xml version="1.0" encoding="UTF-8"?>
<leadsheets 
	xmlns="http://freebits.de/OMT-engine/schemas/Leadsheets" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://freebits.de/OMT-engine/schemas/Leadsheets Leadsheets.xsd "
	num="124">
    <leadsheet id="1" is-a-id="0" title="Falling In Love Again">
        <voice reference-id="41" meaning="chord" deltatime="0.0000" deltatone="3"></voice>
        <voice reference-id="1383" meaning="melody" deltatime="0.0000" basicnote="70"></voice>
    </leadsheet>
    <leadsheet id="80" is-a-id="0" title="Morgen Kommt Der Weihnachtsmann">
        <voice reference-id="125" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1415" meaning="melody" deltatime="0.0000" basicnote="65"></voice>
    </leadsheet>
    <leadsheet id="81" is-a-id="80" title="Morgen Kommt Der Weihnachtsmann">
        <voice reference-id="125" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1415" meaning="melody" deltatime="0.0000" basicnote="65"></voice>
        <voice reference-id="9" meaning="accompaniment" deltatime="0.0000" basicnote="62"></voice>
    </leadsheet>
    <leadsheet id="101" is-a-id="0" title="Alouette">
        <voice reference-id="13" meaning="chord" deltatime="0.0000" deltatone="7"></voice>
        <voice reference-id="1355" meaning="melody" deltatime="0.0000" basicnote="67"></voice>
    </leadsheet>
    <leadsheet id="102" is-a-id="0" title="Angel eyes">
        <voice reference-id="14" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1471" meaning="melody" deltatime="0.1660" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="103" is-a-id="0" title="Auld lang syne">
        <voice reference-id="16" meaning="chord" deltatime="1.0000" deltatone="7"></voice>
        <voice reference-id="1359" meaning="melody" deltatime="1.0000" basicnote="67"></voice>
    </leadsheet>
    <leadsheet id="104" is-a-id="0" title="Autumn Leaves">
        <voice reference-id="17" meaning="chord" deltatime="1.0000" deltatone="9"></voice>
        <voice reference-id="1360" meaning="melody" deltatime="0.2500" basicnote="64"></voice>
    </leadsheet>
    <leadsheet id="105" is-a-id="106" title="Ain't Misbehavin">
        <voice reference-id="3" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1345" meaning="melody" deltatime="0.1250" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="106" is-a-id="0" title="Ain't Misbehavin">
        <voice reference-id="4" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1346" meaning="melody" deltatime="0.1250" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="107" is-a-id="108" title="Alice in Wonderland">
        <voice reference-id="5" meaning="chord" deltatime="0.0000" deltatone="2"></voice>
        <voice reference-id="1347" meaning="melody" deltatime="0.0000" basicnote="67"></voice>
    </leadsheet>
    <leadsheet id="108" is-a-id="0" title="Alice in Wonderland">
        <voice reference-id="6" meaning="chord" deltatime="0.0000" deltatone="2"></voice>
        <voice reference-id="1348" meaning="melody" deltatime="0.0000" basicnote="67"></voice>
    </leadsheet>
    <leadsheet id="109" is-a-id="117" title="All of me">
        <voice reference-id="7" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1349" meaning="melody" deltatime="0.0000" basicnote="72"></voice>
    </leadsheet>
    <leadsheet id="110" is-a-id="0" title="All the things you are">
        <voice reference-id="8" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1351" meaning="melody" deltatime="0.0000" basicnote="68"></voice>
    </leadsheet>
    <leadsheet id="111" is-a-id="0" title="House of the rising sun">
        <voice reference-id="55" meaning="chord" deltatime="0.7500" deltatone="9"></voice>
        <voice reference-id="1397" meaning="melody" deltatime="0.6250" basicnote="64"></voice>
    </leadsheet>
    <leadsheet id="112" is-a-id="0" title="Guten Abend, Gute Nacht">
        <voice reference-id="48" meaning="chord" deltatime="0.7500" deltatone="3"></voice>
        <voice reference-id="1389" meaning="melody" deltatime="0.5000" basicnote="67"></voice>
    </leadsheet>
    <leadsheet id="113" is-a-id="114" title="A Foggy Day">
        <voice reference-id="45" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1386" meaning="melody" deltatime="0.2500" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="114" is-a-id="0" title="A Foggy Day">
        <voice reference-id="46" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1387" meaning="melody" deltatime="0.2500" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="115" is-a-id="0" title="Alle Voegel sind schon da">
        <voice reference-id="10" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1352" meaning="melody" deltatime="0.0000" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="116" is-a-id="0" title="A night in tunesia">
        <voice reference-id="79" meaning="chord" deltatime="0.0000" deltatone="3"></voice>
        <voice reference-id="1480" meaning="melody" deltatime="0.0000" basicnote="51"></voice>
    </leadsheet>
    <leadsheet id="117" is-a-id="0" title="All of me">
        <voice reference-id="7" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1350" meaning="melody" deltatime="0.0000" basicnote="72"></voice>
    </leadsheet>
    <leadsheet id="118" is-a-id="0" title="Biene Maja">
        <voice reference-id="24" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1369" meaning="melody" deltatime="0.1250" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="119" is-a-id="0" title="White Christmas">
        <voice reference-id="114" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1461" meaning="melody" deltatime="0.0000" basicnote="64"></voice>
    </leadsheet>
    <leadsheet id="120" is-a-id="0" title="Komm Lieber Mai">
        <voice reference-id="62" meaning="chord" deltatime="0.7500" deltatone="2"></voice>
        <voice reference-id="1406" meaning="melody" deltatime="0.6250" basicnote="62"></voice>
    </leadsheet>
    <leadsheet id="121" is-a-id="0" title="Jingle Bells">
        <voice reference-id="61" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1479" meaning="melody" deltatime="0.0000" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="122" is-a-id="0" title="When the saints">
        <voice reference-id="113" meaning="chord" deltatime="1.0000" deltatone="0"></voice>
        <voice reference-id="1460" meaning="melody" deltatime="0.2500" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="123" is-a-id="0" title="Unchain my heart">
        <voice reference-id="108" meaning="chord" deltatime="1.0000" deltatone="9"></voice>
        <voice reference-id="1490" meaning="melody" deltatime="0.2500" basicnote="69"></voice>
    </leadsheet>
    <leadsheet id="124" is-a-id="0" title="Bridal Chorus (Hochzeitsmarsch)">
        <voice reference-id="29" meaning="chord" deltatime="2.0000" deltatone="10"></voice>
        <voice reference-id="1475" meaning="melody" deltatime="2.0000" basicnote="65"></voice>
    </leadsheet>
    <leadsheet id="125" is-a-id="0" title="A Felicidade">
        <voice reference-id="1" meaning="chord" deltatime="1.0000" deltatone="0"></voice>
        <voice reference-id="1470" meaning="melody" deltatime="1.0000" basicnote="72"></voice>
    </leadsheet>
    <leadsheet id="126" is-a-id="0" title="Almost Like Being In Love ">
        <voice reference-id="11" meaning="chord" deltatime="1.0000" deltatone="3"></voice>
        <voice reference-id="1353" meaning="melody" deltatime="0.5000" basicnote="70"></voice>
    </leadsheet>
    <leadsheet id="127" is-a-id="0" title="Au Privave ">
        <voice reference-id="15" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1027" meaning="melody" deltatime="0.0000" basicnote="65"></voice>
    </leadsheet>
    <leadsheet id="129" is-a-id="0" title="Wave">
        <voice reference-id="110" meaning="chord" deltatime="1.0000" deltatone="5"></voice>
        <voice reference-id="1454" meaning="melody" deltatime="0.6250" basicnote="62"></voice>
    </leadsheet>
    <leadsheet id="130" is-a-id="0" title="The little drummer boy">
        <voice reference-id="64" meaning="chord" deltatime="0.0000" deltatone="5"></voice>
        <voice reference-id="1408" meaning="melody" deltatime="0.0000" basicnote="65"></voice>
    </leadsheet>
    <leadsheet id="131" is-a-id="0" title="Zip a Dee Doo Dah">
        <voice reference-id="122" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1469" meaning="melody" deltatime="0.0000" basicnote="64"></voice>
    </leadsheet>
    <leadsheet id="133" is-a-id="0" title="National Anthem- Germany">
        <voice reference-id="77" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1420" meaning="melody" deltatime="0.0000" basicnote="60"></voice>
    </leadsheet>
    <leadsheet id="134" is-a-id="138" title="You Are The Sunshine Of My Life">
        <voice reference-id="120" meaning="chord" deltatime="0.0000" deltatone="0"></voice>
        <voice reference-id="1487" meaning="melody" deltatime="0.2500" basicnote="59"></voice>
    </leadsheet>
    <leadsheet id="136" is-a-id="137" title="My Favorite Thing">
